version: "3"
services:
  app:
    build: ./docker/php
    container_name: app
    volumes:
      - ./backend:/work

  web:
    image: nginx:1.20-alpine
    container_name: web
    ports:
      - 8080:80
    volumes:
      - ./backend:/work
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work