version: "3"

volumes:
  postgres:

    null
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    user: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: "Asia/Tokyo"
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d

  api:
    build: ./docker/php
    container_name: api
    depends_on:
      - postgres
    volumes:
      - ./backend:/work

  nginx-api:
    image: nginx:1.20-alpine
    container_name: nginx-api
    ports:
      - 8080:80
    volumes:
      - ./backend:/work
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work

  vue:
    container_name: vue
    build: ./docker/node
    working_dir: /workspace
    volumes:
      - ./frontend/vue-cli-ui:/root/.vue-cli-ui
      - ./frontend/workspace:/workspace
    ports:
      - "8000:8000"
      - "8081-8089:8081-8089"
    command: "vue ui --host=0.0.0.0 --port=8000"
